In [1]:
from NiCro import NiCro

In [2]:
nicro = NiCro()

In [3]:
nicro.get_devices_info()

Selected Source Device:
Device ID:0 Name:emulator-5554 Resolution:Size(width=1080, height=2280)

All Devices:
Device ID:0 Name:emulator-5554 Resolution:Size(width=1080, height=2280)
Device ID:1 Name:emulator-5556 Resolution:Size(width=1080, height=1920)


In [4]:
nicro.detect_gui_info_for_all_devices(is_load=False)

****** Device [1 / 2] ******
[Text Detection Completed in 1.447 s] Input: data/screen/emulator-5554.png Output: data/output/ocr/emulator-5554.json
[Compo Detection Completed in 0.421 s] Input: data/screen/emulator-5554.png Output: data/output/ip/emulator-5554.json
[Merge Completed] Input: data/screen/emulator-5554.png Output: data/output/merge/emulator-5554.jpg
****** Device [2 / 2] ******
[Text Detection Completed in 0.134 s] Input: data/screen/emulator-5556.png Output: data/output/ocr/emulator-5556.json
[Compo Detection Completed in 0.543 s] Input: data/screen/emulator-5556.png Output: data/output/ip/emulator-5556.json
[Merge Completed] Input: data/screen/emulator-5556.png Output: data/output/merge/emulator-5556.jpg


In [5]:
nicro.control_multiple_devices_through_source_device(is_replay=True)

In [6]:
resnet_model = nicro.resnet_model

In [7]:
import cv2
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
clips1 = [cv2.resize(ele.clip, (32, 32), interpolation=cv2.INTER_AREA) for ele in nicro.devices[0].GUI.elements]
clips2 = [cv2.resize(ele.clip, (32, 32), interpolation=cv2.INTER_AREA) for ele in nicro.devices[1].GUI.elements]

In [9]:
encodings = resnet_model.predict(np.array(clips1 + clips2))
encodings = encodings.reshape((encodings.shape[0], -1))
sim_matrix = cosine_similarity(encodings[:len(clips1)], encodings[len(clips1):])

In [46]:
select = np.where(sim_matrix[11] > 0.8)[0]

In [48]:
select

array([19, 21, 22, 25, 26, 28, 29])

In [87]:
eles = np.array(nicro.devices[1].GUI.elements)

In [22]:
ids = [e.id for e in nicro.devices[1].GUI.elements]

In [49]:
set(select).intersection(set(ids))

{19, 21, 22, 25, 26, 28, 29}

In [37]:
select

(array([], dtype=int64),)

In [11]:
from element_matching.matching import *

In [20]:
sm = np.array(image_similarity_matrix(clips1, clips2, method='dhash', resnet_model=resnet_model))

In [24]:
np.argmax(sm)

154

In [21]:
np.where(sm > 0.8)

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,
         8, 12, 12, 12, 12, 13, 13, 16, 17, 17, 17, 17, 17, 17, 17, 17, 18,
        18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20,
        20, 22, 32]),
 array([ 4,  6,  8, 11, 14, 15, 16, 17,  0,  1,  2,  3,  4,  6,  8, 10, 11,
        14, 15, 16, 17,  4,  6,  8, 14, 15, 16,  4,  6,  8, 14, 15, 16, 17,
         9,  4, 10, 14, 17, 11, 12, 13,  4,  6,  8, 10, 14, 15, 16, 17,  4,
         6,  8, 14, 15, 16,  4,  6,  8, 14, 15, 16, 17,  4,  6, 10, 14, 15,
        17, 18, 29]))

In [23]:
np.where(sim_matrix > 0.8)

(array([ 1,  2,  3,  4,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,
         6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  8,  9,  9, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 13,
        16, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 22, 22, 23, 23, 23,
        23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26,
        26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
        28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29,
        29, 29, 29, 29, 29, 29, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32]),
 array([ 0,  1,  2,  3,  4,  6,  8, 12, 14, 15, 16, 20,  4,  6,  8, 12, 14,
        15, 16, 20,  4,  6,  8, 12, 14, 15, 16, 20,  9, 26, 29, 19, 21, 22,
        23, 24, 25, 26, 28, 29, 19, 21, 22